#ifndef PINS_H
#define PINS_H

#define WHEEL_MOTOR1_PWM_PIN 32
#define WHEEL_MOTOR1_DIR_PIN 15 // 本来は33!!
#define WHEEL_MOTOR2_PWM_PIN 25
#define WHEEL_MOTOR2_DIR_PIN 26
#define WHEEL_MOTOR3_PWM_PIN 27
#define WHEEL_MOTOR3_DIR_PIN 14
#define PHOTO_SENSOR1_PIN 12
#define PHOTO_SENSOR2_PIN 13
#define PHOTO_SENSOR3_PIN 15
#define BNO055_SDA_PIN 21
#define BNO055_SCL_PIN 22
#define ARM_SERVO1_PIN 4
#define ARM_SERVO2_PIN 5
#define BELT_MOTOR_DIR_PIN 12
#define BELT_MOTOR_PWM_PIN 19
#define SWITCH_PIN 23

#endif